# coding=utf-8
import os
import sys
import json
import subprocess
import shutil

def translate_pdf(input_pdf, output_pdf):
    print(f"Start translating {input_pdf} using PDFMathTranslate")
    from dotenv import load_dotenv
    env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), ".env")
    load_dotenv(env_path)
    
    api_key = os.environ.get("TRANSLATE_API_KEY") or os.environ.get("CHAT_API_KEY", "")
    api_url = os.environ.get("TRANSLATE_API_URL") or os.environ.get("CHAT_API_URL", "https://api.siliconflow.cn/v1")
    model_name = os.environ.get("TRANSLATE_MODEL") or os.environ.get("CHAT_MODEL", "Qwen/Qwen2.5-7B-Instruct")
    
    import tempfile
    env = os.environ.copy()
    if api_key:
        env["OPENAI_API_KEY"] = api_key
    if api_url:
        env["OPENAI_BASE_URL"] = api_url
    env["HF_ENDPOINT"] = "https://hf-mirror.com"
    
    # Create safe tmp names
    tmp_fd, safe_input_pdf = tempfile.mkstemp(suffix=".pdf", prefix="translate_in_")
    os.close(tmp_fd)
    shutil.copy(input_pdf, safe_input_pdf)
    safe_basename = os.path.splitext(os.path.basename(safe_input_pdf))[0]
    safe_dir = os.path.dirname(safe_input_pdf)
    safe_mono_pdf = os.path.join(safe_dir, f"{safe_basename}-zh.pdf")
    safe_dual_pdf = os.path.join(safe_dir, f"{safe_basename}-dual.pdf")
    
    # Using 10 threads max for silicon
    cmd = [
        sys.executable, "-m", "pdf2zh.pdf2zh",
        safe_input_pdf,
        "-s", f"openai:{model_name}",
        "-t", "4"
    ]
    
    print(f"Executing: {' '.join(cmd)}")
    
    try:
        # Run process synchronously
        subprocess.run(cmd, env=env, cwd=os.path.dirname(safe_input_pdf), check=True)
    except Exception as e:
        print(f"Exception while running pdf2zh: {e}")
        sys.exit(1)

    # Output files generated by pdf2zh
    import glob
    possible_monos = glob.glob(os.path.join(safe_dir, f"{safe_basename}-*.pdf"))
    possible_monos = [f for f in possible_monos if f != safe_input_pdf and not f.endswith("-dual.pdf")]
    
    if possible_monos:
        safe_mono_pdf = possible_monos[0]
        print(f"Moving {safe_mono_pdf} -> {output_pdf}")
        try:
            # Overwrite if exists
            if os.path.exists(output_pdf):
                os.remove(output_pdf)
            shutil.move(safe_mono_pdf, output_pdf)
            print("Translation complete!")
        except Exception as e:
            print(f"Failed moving output pdf: {e}")
            sys.exit(1)
            
    else:
        print("Error: Translated mono PDF not found!")
        sys.exit(1)
        
    # Cleanup safe temp files
    for tmp_f in [safe_input_pdf, safe_mono_pdf, safe_dual_pdf]:
        try:
            if os.path.exists(tmp_f):
                os.remove(tmp_f)
        except:
            pass
        
if __name__ == "__main__":
    if len(sys.argv) > 2:
        translate_pdf(sys.argv[1], sys.argv[2])
