# coding=utf-8
import os
import sys
import json
import subprocess
import shutil

def translate_pdf(input_pdf, output_pdf):
    print(f"Start translating {input_pdf} using PDFMathTranslate")
    cfg_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.json")
    api_key = ""
    if os.path.exists(cfg_path):
        with open(cfg_path, "r", encoding="utf-8") as f:
            cfg = json.load(f)
        api_key = cfg.get("translate_api_key", cfg.get("chat_api_key", ""))
    
    import tempfile
    
    env = os.environ.copy()
    if api_key:
        env["SILICON_API_KEY"] = api_key
    env["HF_ENDPOINT"] = "https://hf-mirror.com"
    
    # Create safe tmp names
    tmp_fd, safe_input_pdf = tempfile.mkstemp(suffix=".pdf", prefix="translate_in_")
    os.close(tmp_fd)
    shutil.copy(input_pdf, safe_input_pdf)
    safe_basename = os.path.splitext(os.path.basename(safe_input_pdf))[0]
    safe_mono_pdf = os.path.join(os.path.dirname(safe_input_pdf), f"{safe_basename}-mono.pdf")
    safe_dual_pdf = os.path.join(os.path.dirname(safe_input_pdf), f"{safe_basename}-dual.pdf")
    
    # Using 10 threads max for silicon
    cmd = [
        sys.executable, "-m", "pdf2zh.pdf2zh",
        safe_input_pdf,
        "-s", "silicon",
        "-t", "4",
        "--ignore-cache"
    ]
    
    print(f"Executing: {' '.join(cmd)}")
    
    try:
        # Run process synchronously
        subprocess.run(cmd, env=env, cwd=os.path.dirname(safe_input_pdf), check=True)
    except Exception as e:
        print(f"Exception while running pdf2zh: {e}")

    # Output files generated by pdf2zh
    if os.path.exists(safe_mono_pdf):
        print(f"Moving {safe_mono_pdf} -> {output_pdf}")
        try:
            # Overwrite if exists
            if os.path.exists(output_pdf):
                os.remove(output_pdf)
            shutil.move(safe_mono_pdf, output_pdf)
            print("Translation complete!")
        except Exception as e:
            print(f"Failed moving output pdf: {e}")
            
    else:
        print("Error: Translated mono PDF not found!")
        
    # Cleanup safe temp files
    for tmp_f in [safe_input_pdf, safe_mono_pdf, safe_dual_pdf]:
        try:
            if os.path.exists(tmp_f):
                os.remove(tmp_f)
        except:
            pass
        
if __name__ == "__main__":
    if len(sys.argv) > 2:
        translate_pdf(sys.argv[1], sys.argv[2])
